#!/bin/bash

EXTRACT_SBOPS=../tools/sandbox_toolkit/extract_sbops/extract_sbops

if ! test -f "$EXTRACT_SBOPS"; then
    echo "Error: extract_sbops executable does not exist at $EXTRACT_SBOPS" 1>&2
    echo "Make sure you compiled it." 1>&2
    exit 1
fi

if test $# -ne 2; then
    echo "Usage: $0 <sandbox-extension> <ios-version>" 1>&2
    echo "" 1>&2
    echo "Arguments the kernel sandbox extension and the iOS version (such as 7, 7.1, 7.1.1) it belongs to" 1>&2
    exit 1
fi

sandbox_kext="$1"
ios_version="${2%%.*}"

if ! [[ "$ios_version" =~ ^[0-9]+$ ]]; then
    echo "Second argument must be an iOS version (such as 7, 7.1, 7.1.1)" 1>&2
    exit 1
fi

echo "Extracting sandbox operations of iOS $2 ..." 1>&2
if test "$ios_version" -le 4; then
    echo "No support for iOS <= 4 yet." 1>&2
    exit 1
elif test "$ios_version" -le 8; then
    "$EXTRACT_SBOPS" "$sandbox_kext"
elif test "$ios_version" -le 11; then
    # Trim extra output. Last correct operations are system-*.
    # Print those and ditch the rest.
    "$EXTRACT_SBOPS" "$sandbox_kext" | awk '
BEGIN {
    found=0;
}
/^system-.*/ {
    print $0;
    found=1;
    next;
}
{
    if (found == 0)
        print $0;
    else
        exit 0;
}'
else
    echo "Unknown or unsupported iOS major version $ios_version" 1>&2
    exit 1
fi
